<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ThroneForge.Content</AssemblyName>
    <RootNamespace>ThroneForge.Content</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ThroneForge.Contracts/ThroneForge.Contracts.csproj" />
    <ProjectReference Include="../ThroneForge.Schemas/ThroneForge.Schemas.csproj" />
  </ItemGroup>
</Project>

