<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.1</TargetFrameworks>
    <AssemblyName>ThroneForge.API</AssemblyName>
    <RootNamespace>ThroneForge.API</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ThroneForge.Contracts/ThroneForge.Contracts.csproj" />
  </ItemGroup>
</Project>
