<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ThroneForge.PluginLoadTest</AssemblyName>
    <RootNamespace>ThroneForge.PluginLoadTest</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ThroneForge.API/ThroneForge.API.csproj" />
    <ProjectReference Include="../ThroneForge.Contracts/ThroneForge.Contracts.csproj" />
    <ProjectReference Include="../ThroneForge.Runtime/ThroneForge.Runtime.csproj" />
  </ItemGroup>
</Project>
